In [1]:
#input adjacency matrix
import numpy as np
d = 0.9 #damping factor
adj = np.array([[0,0.5,0.5,0,0,0],[0,0,0,0,0,0],[0.5,0,0,0,0.5,0],[0,0,0,0,0.5,0.5],[0,0,0,0.5,0,0.5],[0,0,0,0.5,0,0]])
print(adj)

[[0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.5 0.  0. ]]


In [2]:
#handling the node with no out going links
n=len(adj)
for i in range(n):
    if any(adj[i])==0:
        for l in range(n):
            adj[i][l]=1/n
print(adj)

[[0.         0.5        0.5        0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.5        0.         0.         0.         0.5        0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         0.5        0.         0.        ]]


In [3]:
#stochastic matrix formation
E = np.ones((n,n))
sto=(1-d)*E/n+d*np.transpose(adj)
print(sto)

[[0.01666667 0.16666667 0.46666667 0.01666667 0.01666667 0.01666667]
 [0.46666667 0.16666667 0.01666667 0.01666667 0.01666667 0.01666667]
 [0.46666667 0.16666667 0.01666667 0.01666667 0.01666667 0.01666667]
 [0.01666667 0.16666667 0.01666667 0.01666667 0.46666667 0.46666667]
 [0.01666667 0.16666667 0.46666667 0.46666667 0.01666667 0.01666667]
 [0.01666667 0.16666667 0.01666667 0.46666667 0.46666667 0.01666667]]


In [4]:
#Page rank of all the six nodes after each iteration
P=[]
P.append(np.ones((n,1))/n)
k=0
e=0.05
c=1
while c:
    P.append((1-d)*np.ones((n,1))+d*np.transpose(adj).dot(P[k]))
    a=abs((P[k+1]-P[k]))<e
    stop = a.all()
    if stop:
        c=0

    k=k+1



In [5]:
#Total number iteration count until stopping criteria.
for i in range(len(P)):
    print('--------------------------------')
    print(f'Iteration {i}')
    
    print(P[i])
    print('--------------------------------')

--------------------------------
Iteration 0
[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]
--------------------------------
--------------------------------
Iteration 1
[[0.2  ]
 [0.2  ]
 [0.2  ]
 [0.275]
 [0.275]
 [0.275]]
--------------------------------
--------------------------------
Iteration 2
[[0.22   ]
 [0.22   ]
 [0.22   ]
 [0.3775 ]
 [0.34375]
 [0.3775 ]]
--------------------------------
--------------------------------
Iteration 3
[[0.232    ]
 [0.232    ]
 [0.232    ]
 [0.4575625]
 [0.401875 ]
 [0.4575625]]
--------------------------------
--------------------------------
Iteration 4
[[0.2392    ]
 [0.2392    ]
 [0.2392    ]
 [0.52154687]
 [0.44510312]
 [0.52154687]]
--------------------------------
--------------------------------
Iteration 5
[[0.24352   ]
 [0.24352   ]
 [0.24352   ]
 [0.5708725 ]
 [0.47821609]
 [0.5708725 ]]
--------------------------------
